/* eslint-disable strict */

const fs = require('fs');

const data = require('../lib/iso3166Data');

const codes = [];
const all = [];
const warning = '/** generated by scripts/split.js */\n\n';

data.forEach((i) => {
	codes.push(
		`/** ${i.country_name} */\nconst ${
			i.alpha3 || i.alpha2
		} = require('../iso3166Data/${i.country_code}_${i.alpha3 || i.alpha2}');`,
	);

	all.push(i.alpha3 || i.alpha2);

	fs.writeFileSync(
		`./iso3166Data/${i.country_code}_${i.alpha3 || i.alpha2}.js`,
		`${warning}module.exports = ${JSON.stringify(i, null, 2)};`,
	);
});

fs.writeFileSync(
	'./lib/allData.js',
	`${warning}${codes.join('\n')}\n\nmodule.exports = ${JSON.stringify(
		all,
		null,
		2,
	).replace(/"/g, '')}`,
);
